# Параметри екрана
WIDTH, HEIGHT = 1100, 700
CELL_SIZE = 40  # Розмір клітинки

GRID_WIDTH, GRID_HEIGHT = 16, 16

FIELD_OFFSET_X = (WIDTH - (GRID_WIDTH * CELL_SIZE)) // 2
FIELD_OFFSET_Y = (HEIGHT - (GRID_HEIGHT * CELL_SIZE)) // 2
